#cloud-config
users:
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer
    groups: users, admin # Zugehörigkeit zu Benutzergruppen
    home: /home/ubuntu # Verzeichnis des Benutzers
    shell: /bin/bash # Standard-Shell für den Benutzer
    ssh_authorized_keys: # SSH-Schlüssel für den Benutzer
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCMY7nD0nMRXuyzDIwXdRmlNIrxfa1yJ10kVpsajF2df07ys/Sahsj34XxrWU/zl43ZvmpfC0q4APhgcFPeOhCb+aFcBnBjBfW6+SxX//CJDubtq1VSbxSM99S9haTWnpuK+yKlvgjLnwVUHALZk+J/bvlvnGd0oilZtBUWtx9EcCgc2McP1ixmnGfYmWfKJ/NieO7GYRLv0VptzISj/Ccm+tzVmdBbAY8mjjxos8kxthuSh4rvQB8OVhL95x3mG26096CdS6D/0G7bIyNeNVDPdCV4Oy6GdVjT/rdU8JeiDkPkVj3l2Ev2lf5kI6JKqYxgNc9m76Wf7a3XZ68vXrab aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: false # SSH-Passwort-Authentifizierung deaktivieren
disable_root: false # Root-Benutzer deaktivieren
package_update: true # Paketaktualisierung durchführen

# Pakete/Software aktualisieren
# Apache Webserver installieren
packages:
  - apache2
  - php
  - libapache2-mod-php

# Datei für PHP-Dateien erstellen
write_files:
  - path: /var/www/html/image.php
    content: |
      <?php $ihrname = "Linus Daniels"; ?>
        <html>
          <head>
          <title><?php echo($ihrname) ?></title>
          </head>
          <body>
          Das ist eine Katze
          <br />
          <img src="https://kn04-bucket-linus-daniels.s3.amazonaws.com/eduardo-gorghetto-5auIBbcoRNw-unsplash.jpg" />
          Platzieren Sie hier notwendige Quellenangaben, z.B. wenn der Inhalt von unsplash kommt.
          Quellenangaben:
          - unsplash.com
          </body>
        </html>