#cloud-config
users:
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer
    groups: users, admin # Zugehörigkeit zu Benutzergruppen
    home: /home/ubuntu # Verzeichnis des Benutzers
    shell: /bin/bash # Standard-Shell für den Benutzer
    ssh_authorized_keys: # SSH-Schlüssel für den Benutzer
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCMY7nD0nMRXuyzDIwXdRmlNIrxfa1yJ10kVpsajF2df07ys/Sahsj34XxrWU/zl43ZvmpfC0q4APhgcFPeOhCb+aFcBnBjBfW6+SxX//CJDubtq1VSbxSM99S9haTWnpuK+yKlvgjLnwVUHALZk+J/bvlvnGd0oilZtBUWtx9EcCgc2McP1ixmnGfYmWfKJ/NieO7GYRLv0VptzISj/Ccm+tzVmdBbAY8mjjxos8kxthuSh4rvQB8OVhL95x3mG26096CdS6D/0G7bIyNeNVDPdCV4Oy6GdVjT/rdU8JeiDkPkVj3l2Ev2lf5kI6JKqYxgNc9m76Wf7a3XZ68vXrab aws-key
ssh_pwauth: false # SSH-Passwort-Authentifizierung deaktivieren
disable_root: false # Root-Benutzer deaktivieren
package_update: true # Paketaktualisierung durchführen
packages: # Installierte Pakete
  - mariadb-server

# Neuen Benutzer erstellen
runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service